### ISSUE TITLE
File structure and love2d

### ISSUE THREAD

**Issue by konsumer** [shironecko/LuaMaze#2]
When using your lib in my game, I had to do a bit of stuff to get around the hard-coded file-structure. What I landed on was [this](https://github.com/notnullgames/lol/tree/main/src/lib/maze) where nothing requires anything else, except init, which requires everything. It still depends on everything in a `maze` dir, but it's easier to restructure (just change init.) this allows people to import maze.lua and a particular generator, if they want, but also get the whole thing at once, if they want that. It could probably be further improved to get the real dir of the current file, and make all requires completely relative.

I also made a [tile-based setup for love](https://github.com/notnullgames/lol/blob/main/src/lib/MazeMap.lua). `build()` will create a bunch of spritebatches (1 for each direction) then `draw()` overlays them all over the top of each other. I could restructure it so it's not so game-specific (it uses a `player` object to determine x/y and has it's own controls/camera), and it might be more useful for others. I used [tiled](https://www.mapeditor.org/) to draw larger tiles that have the shape I want, from existing tiles I was already using.  It could probably be further improved by just defining `floor` and `wall` and drawing the shapes with smaller tiles, directly to a single spritebatch. Maybe even a concept of tile-pools, for variance, like several different tiles that could be placed in a "wall" or "floor", automatically, that have little differences like cracks and stuff.

![Screenshot from 2021-02-13 15-22-20](https://user-images.githubusercontent.com/83857/107864267-597f1e80-6e0f-11eb-85ca-1519743df85f.png)

![Screenshot from 2021-02-13 15-23-45](https://user-images.githubusercontent.com/83857/107864279-829faf00-6e0f-11eb-8f1c-bd0159a68cf4.png)

Are you interested in a PR for these ideas?

**Comment by shironecko** [comment]
Sure! I'm open to PRs and what you described does make a lot of sence.
Moreover, since I've long moved onto more low-level development and forgot how to even Lua, I'm open to giving push rights to anyone who's interested in improving and maintaining the lib (since it seems to be useful to at least a couple of people).
Let me know if that sounds interesting to you.

**Comment by konsumer** [comment]
It appears my link above is dead now. [Here](https://gist.github.com/konsumer/df3cccafda21248eb69d52742294cd2b) is the basic idea, using player-position, a hump camera, and love2d spritebatches. I have switched to godot for our game engine. it makes a lot of things easier to work with, and has been a lot of fun.

That said, your lib helped me write maze algos in gdscript, as it's a great collection of simple code, written very legibly, that illustrates the ideas in a simple way in lua, so I'm into helping make it more useful for others. I feel like if nothing else, it's a good educational collection of how to make mazes in a simple scripting language, and it's super-useful. I can make a PR for the above things (restructure files and love2d render-layer.)

As for maintenance, I dunno. It doesn't seem like this project gets a lot of traffic, so it might be ok, but I am very busy and have a lot of projects I currently support (probly way too many!) so I am reluctant to take it on. I could be a co-maintainer, if you wanted to share the burden. Between the 2 of us, we could probly handle the occasional issues that come through.

**Comment by konsumer** [comment]
Maybe a PR for the file-restructure, and add a self-contained love thing, and I could make a separate "demo project" that is just a love game with hump camera, etc?

**Comment by shironecko** [comment]
I actually wrote this project 7 years ago just to learn Lua and have been surprised that some people found and starred it. Since I mostly do really weird experimental stuff, like hot-reloading C code, I was surprised that one of my project was useful to someone 😅 

About maintenance, it's fine if you don't feel up to it, life's too short, especially with many projects to maintain 😅 
But I'd still be grateful for a PR since you already have some stuff cooked up.
I'll try to pick up the project once I finish the stuff I'm working on right now, it never sat well with me that it was so close to completion but never was actually completed. Better file structure + actual Wiki could make it into a decent learning resource indeed.

**Comment by konsumer** [comment]
I hear that. I'd love to help. As I said, it was very helpful to me, in order to grock how maze-generation works, even though I didn't end up using any of the code. I actually have the original maze author's book about generating mazes on my bookshelf, but this was much more helpful in actually understanding it.

**Comment by konsumer** [comment]
Maybe once I make more progress with it in godot, we can link to each other, too. My original goal was to make a simple-to-use godot plugin that can do all the same stuff, but I got lazy about it. I feel like both projects might help people better understand maze-generation and procedural level-generating, in general.

**Comment by konsumer** [comment]
How would you feel about dropping frames? I can't seem to find a good copy of it. The linked gitmodule seems dead, and I tried `eledot/LoveFrames`, but it throws a `attempt to call field 'setStencil' (a nil value)`. Not sure of a good alternative lib. Do you have a preference?

**Comment by konsumer** [comment]
I just went with [ListBox](https://github.com/darkmetalic/ListBox):

![Screenshot from 2021-03-17 16-41-01](https://user-images.githubusercontent.com/83857/111552478-a8d2aa80-873f-11eb-9825-d2ef4bc6cc75.png)

**Comment by konsumer** [comment]
Ok, that PR should be GTG. Nothing fancy, just minor restructure, a CLI demo, replaced frames with listbox, and made a tiled-demo, and libraryized the love stuff. I ended up having to add this to init.lua to do relative-imports, totally fine with doing it some other way, if you know of a better way:

```lua
local requireRel
if arg and arg[0] then
    package.path = arg[0]:match("(.-)[^\\/]+$") .. "?.lua;" .. package.path
    requireRel = require
elseif ... then
    local d = (...):match("(.-)[^%.]+$")
    function requireRel(module) return require(d .. module) end
end
```

It's basically just a convenience-wrapper around importing them all seperately, and totally optional if users want to import only what they need.

**Comment by shironecko** [comment]
Hey! Sorry for disappearing for a couple of days, I was finishing a loooong and stressful contract. On the bright side it's over now so I'll be able to devote a lot more time to issues and PRs.

I just merged your PR, thank for this amazing contribution! :)
